chore(push): Update push script to push the all tags on release
litmuschaos/chaos-operator pull request #315
Opened 2020-12-21 09:20 UTC by uditgaurav

Signed-off-by: udit <udit.gaurav@mayadata.io>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] Labelled this PR & related issue with `documentation` tag
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests

2020-12-22 12:10 UTC, rajdas98 requested changes

2020-12-22 12:10 UTC, rajdas98 commented on buildscripts/push
> +    docker buildx build --file build/Dockerfile --progress plane --push --platform linux/arm64,linux/amd64 --tag ${REPONAME}/${IMGNAME}:ci .
You can build multiple tags from a single command.
```suggestion
    echo "Building ${REPONAME}/${IMGNAME}:ci ..."
    docker buildx build --file build/Dockerfile --progress plane --push --platform linux/arm64,linux/amd64 --tag ${REPONAME}/${IMGNAME}:latest -tag ${REPONAME}/${IMGNAME}:ci .    
```

2021-03-11 08:31 UTC, uditgaurav commented
/run-e2e

2021-03-11 09:10 UTC, ksatchit approved these changes

2021-03-11 09:10 UTC, merged